### ISSUE TITLE
Code repetition

### ISSUE THREAD

**Issue by Mochitto** [meganlynn21/Password-Validator#2]
- From line 52 to line 67, there are four list comprehensions in the "any" functions.
It means that you process the password four times (actually, five, with the characters counting process).

As I said, for loops are "heavy" and their number should be kept as small as possible; every function that checks EVERYTHING in the iterable, is the same as a for loop (also, it's best to use built-in functions whenever possible, since they could be working in C instead of python, being much faster).

I suggest using a for loop in the beginning, process the password characters one time and divide them in the preferred groups:
One for upper
One for lower
One for digits 
One for specials (I believe some specials are missing)
And so on...
You could also check if it's faster to count the characters in this for loop OR if the built-in counter() function is more efficient.
You could use any in the end, to check if all of your requirements are satisfied, so that you have only one continue in this part. 

----------------

- Line 42-44; don't duplicate code to check if there is an instance of lower and uppercase of the same thing. 
What if password was "pAsSword1234"? This will give you bugs.
Make the string lowercase and check it against only one lowercase example. 

I also suggest making a list of bad passwords (and to put them in another file, for you to import, so that the main doesn't get clustered) and iterating over them (you could also move to another file the bad input functions, so that the main is easier to read).
Although not necessary, the best thing (if you don't want to add other stuff YET) would be to just leave "pass" inside this list. 
It may seem useless or something that makes the code more complex, but it makes for very, very good maintainability (that is, in the future you can add "bad passwords" easily, if you find out that your users have a problem about their password being easily stolen).

```
bad_passwords = ["pass"]
For bad_pass in bad_passwords:
    If bad_pass.lower() in password.lower():
         (error/message)
         continue (going back to the beginning of the while loop)
```

-------------

You also don't really need to use recursion if you have a while loop at the beginning of the function (on the line where you do the first check, to make sure the user inputted something).
A continue is more readable and less prone to errors. 
You put "main(8,12)" in the recursion; what if in the future you use the function for (1,20)?
If it hits the recursion, the function will now have, as a range, 8-12.
You might forget about the recursion or introduce bugs.
If you do need to use recursion and your function has parameters, make sure to pass in those in the recursion, instead of writing new ones.

**Comment by meganlynn21** [comment]
Thanks a bunch I really appreciate your help
